config/routes.rb
Skygodlin::Application.routes.draw do

  resources :members, :except => [:new, :create]

  resources :roles

  devise_for :users
  resources :users, :only => [:index, :show]   do
    member do
      get :valid
    end
  end

  resources :accounts, :only => [:index, :show]
  constraints(AccountRoute) do
    match '/' => 'sites#index'
    match '/opps' => 'sites#opps'
  end

  get "users/new"

  match '/signup',  :to => 'devise/registrations#new'

  match '/about',   :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  match '/help',    :to => 'pages#help'
  match '/terms',   :to => 'pages#terms'
  match '/privacy', :to => 'pages#privacy'

  root :to => "home#index"

end

app/views/layouts/_footer.html.haml
%footer
  %nav.round
    %ul
      %li= link_to_unless_current "About", about_path
      |
      %li= link_to_unless_current "Help", help_path
      |
      %li= link_to_unless_current "Home", root_path
      |
      %li= link_to_unless_current "Contact", contact_path
      |
      %li= link_to_unless_current "Terms of Use", terms_path
      |
      %li= link_to_unless_current "Privacy Policy", privacy_path
      |
      - if user_signed_in?
        %li
          = link_to_unless_current('Edit account', edit_user_registration_path)
      - else
        %li
          = link_to_unless_current('Sign up', new_user_registration_path)
      |
      - if user_signed_in?
        %li
          = link_to('Logout', destroy_user_session_path)
      - else
        %li
          = link_to_unless_current('Login', new_user_session_path)

app/views/layouts/_header.html.haml
%header
  = link_to logo, root_path
  %nav.round
    %ul
      = render 'devise/menu/registration_items'
      = render 'devise/menu/login_items'

app/views/layouts/_stylesheets.html.haml
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
= stylesheet_link_tag 'blueprint/screen', :media => 'screen'
= stylesheet_link_tag 'blueprint/print',  :media => 'print'
= stylesheet_link_tag 'compiled/screen', :media => 'screen, projection'
= stylesheet_link_tag 'compiled/print', :media => 'print'
= stylesheet_link_tag 'compiled/buttons', :media => 'print'
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= title
    = csrf_meta_tag
    = render 'layouts/stylesheets'
  %body
    .container
      = render 'layouts/header'
      %section.round
        %p{:style => "color: green"}= notice
        %p{:style => "color: red"}= alert
        = yield
      = render 'layouts/footer'