config/routes.rb
Skygodlin::Application.routes.draw do

  resources :members, :except => [:new, :create]

  resources :roles

  devise_for :users
  resources :users, :only => [:index, :show]   do
    member do
      get :valid
    end
  end

  resources :accounts, :only => [:index, :show]
  constraints(AccountRoute) do
    match '/' => 'sites#index'
    match '/opps' => 'sites#opps'
  end

  get "users/new"

  match '/signup',  :to => 'devise/registrations#new'

  match '/about',   :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  match '/help',    :to => 'pages#help'
  match '/terms',   :to => 'pages#terms'
  match '/privacy', :to => 'pages#privacy'

  root :to => "home#index"

end

app/models/member.rb
class Member < User
  
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  # GET /members
  # GET /members.xml
  before_filter :require_user
  before_filter :new
  load_and_authorize_resource
  before_filter :test
  def index
    @members = Member.where(:account_id => current_user.account_id)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @members }
    end
  end

  # GET /members/1
  # GET /members/1.xml
  def show
    #@member = Member.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @member }
    end
  end

  # GET /members/new
  # GET /members/new.xml
  def new
    #new is not valid route, if id = new, redirect
    if params[:id] == "new"
      redirect_to :members, :alert => "New action on members disabled, use invite"
    end
  end

  # GET /members/1/edit
  def edit
    #@member = Member.find(params[:id])
  end


  # PUT /members/1
  # PUT /members/1.xml
  def update
    #@member = Member.find(params[:id])

    respond_to do |format|
      if @member.update_attributes(params[:member])
        format.html { redirect_to(@member, :notice => 'Member was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @member.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.xml
  def destroy
    #@member = Member.find(params[:id])
    @member.destroy

    respond_to do |format|
      format.html { redirect_to(members_url) }
      format.xml  { head :ok }
    end
  end
  
  def test
    if @member
      check_my_account(@member.account.name)
    end
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :login %><br />
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :roles %><br />
    <%= f.text_field :roles %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<h1>Listing members</h1>
  <div class="index-list">
  <table>
    <tr>
      <th>Login</th>
      <th>Name</th>
      <th>Email</th>
      <th>Sign in count</th>
      <th>Roles</th>
      <th>Actions</th>
    </tr>

  <% @members.each do |member| %>
    <tr>
      <td><%= member.login %></td>
      <td><%= member.name %></td>
      <td><%= member.email %></td>
      <td><%= member.sign_in_count %></td>
      <td><%= member.roles %></td>
      <td><%= link_to 'Show', member %>
      <%= link_to 'Edit', edit_member_path(member) %>
      <%= link_to 'Destroy', member, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
  </table>
</div>
<br />

<%= link_to 'Invite New Member', new_user_invitation_path %>

app/views/members/show.html.erb
<p>
  <b>Login:</b>
  <%= @member.login %>
</p>

<p>
  <b>Name:</b>
  <%= @member.name %>
</p>

<p>
  <b>Email:</b>
  <%= @member.email %>
</p>

<p>
  <b>Sign in count:</b>
  <%= @member.sign_in_count %>
</p>

<p>
  <b>Roles:</b>
  <%= @member.roles %>
</p>


<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>