config/routes.rb
Skygodlin::Application.routes.draw do

  resources :members, :except => [:new, :create]

  resources :roles

  devise_for :users
  resources :users, :only => [:index, :show]   do
    member do
      get :valid
    end
  end

  resources :accounts, :only => [:index, :show]
  constraints(AccountRoute) do
    match '/' => 'sites#index'
    match '/opps' => 'sites#opps'
  end

  get "users/new"

  match '/signup',  :to => 'devise/registrations#new'

  match '/about',   :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  match '/help',    :to => 'pages#help'
  match '/terms',   :to => 'pages#terms'
  match '/privacy', :to => 'pages#privacy'

  root :to => "home#index"

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :users
  validates_uniqueness_of :name, :case_sensitive => false
  validates_presence_of :name
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  before_filter :find_user, :except => [:index, :show]
  respond_to :html

  def index
    @accounts = Account.all
    respond_with(@accounts)
  end

  def show
    @account = Account.find(params[:id])
    @admin = User.find(@account.user_id)
    respond_with(@account)
  end

  def new
    @title = "Sign up"
    @account = Account.new(:user => @user)
    respond_with(@account)
  end

  def create
    @account = Account.new(params[:account])
    if @account.save
      flash[:notice] = "Successfully created account."
    end
    redirect_to @user
  end

  def edit
    @account = Account.find(params[:id])
    respond_with(@account)
  end

  def update
    @account = Account.find(params[:id])
    if @account.update_attributes(params[:account])
      flash[:notice] = "Successfully updated account."
    end
    respond_with(@account)
  end

  def destroy
    @account = Account.find(params[:id])
    @account.destroy
    flash[:notice] = "Successfully destroyed account."
    redirect_to @user
  end

  protected

    def find_user
      if params[:user_id]
        @user = User.find(params[:user_id])
      else
        @account = Account.find(params[:id])
        @user = @account.user
      end
      unless current_user == @user
        redirect_to @user, :alert => "Are you logged in properly? You are not allowed to create or change someone else's account."
      end
    end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<% if @account.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>
    <ul>
    <% @account.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= fields_for @account do |f| %> 
  <div>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.hidden_field (:user_id, :value => @account.user_id) %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>
<%= form_for(@account) do |f| %>
  <%= render 'form' %>
<% end %><%= link_to 'Show', @account %> |
<%= link_to @account.user.name, user_path(@account.user) %>

app/views/accounts/index.html.erb
<h1>Accounts</h1>
<table>
<% @accounts.each do |account| %>
  <tr>
    <td><%= link_to account.name, account %></td>
  </tr>
<% end %>
</table>

app/views/accounts/new.html.erb
<h1>New account</h1>
<%= form_for([@user, @account]) do |f| %>
  <%= render 'form' %>
<% end %>
<%= link_to @account.user.name, user_path(@account.user) %>

app/views/accounts/show.html.erb
<h1><%= @account.name %></h1>
<p>Belongs to: <%= link_to @admin.name, user_url(@admin) %></p>